### ISSUE TITLE
QSIgnore does not appear to work

### ISSUE THREAD

**Issue by blueberrycake** [Bogdanp/quicksilver.vim#4]
Using QSIgnore as specified in the documentation, does not appear to work correctly.

Added the following line to vimrc, however .zip files are still showing up on list of available files. Same issue with other extensions

    let g:QSIgnore = "\\.zip$"

Win 7 x64 / Vim 7.3 / Python 2.7.3 32-bit / latest version of Quicksilver from Git

**Comment by Bogdanp** [comment]
#5 should address this.
